# @package _global_
training:
  batch_size: 8
  lr: 0.0001
  epochs: 10
  num_workers: 4
  # Where to save the best checkpoint (by validation accuracy)
  checkpoint_path: ${hydra:runtime.cwd}/best_model_${hydra:runtime.choices.experiment}.pt
  device: cuda
  # Padding Module
  padding_weights_path: ${hydra:runtime.cwd}/padding_module.pt
  padding_epochs: 5
  padding_batch_size: 16
  padding_lr: 1.0e-3
  padding_hidden: 64
  padding_context: 8
  padding_max_samples: 2000

  # LearnedRotation transform
  use_learned_rotation: false         #décisif
  learned_rot_pad_size: 28      
  learned_rot_degrees: 10.0a

use_augment: false                    #décisif
color_prob: 0.8
color_strength: 0.4
blur_prob: 0.15
motion_blur_prob: 0.15
pixelation_prob: 0.15      
flip_prob: 0.5                        #décisif

use_mixup: false
mixup_alpha: 0.2

#Temporal reverse map 
use_temporal_map : false                #décisif