# @package _global_
model:
  name: vit_temporal
  pretrained: true
  num_classes: ${num_classes}
  num_frozen_blocks: 6    # freeze first 6 of 12 ViT-B blocks
  dropout: 0.3
  temporal_layers: 2
  temporal_heads: 8
